[Project]
PROJECT_NAME = Epigen


[Scripts]
ANCESTRY_SPLITTER = /media/lucasf/NAS/PRS_GP2/Scripts/vcf_LAI_pedro-main/vcf_maker.py
FILTRAR_VARIANTES = /media/lucasf/NAS/PRS_GP2/Scripts/filtrar_variantes.py
[Paths]
VCF_FILE = /media/lucasf/NAS/PRS_GP2/Database/GeneticData/Phased_vcf/Phased_1KGP_Peru_Chr@.vcf
MSP_FILE = /media/lucasf/NAS/PRS_GP2/Database/LA/@_query_results.msp

#o nome da pop tem que estar igual do header LAI
SUMSTATS_FILE_ANCESTRY = /media/lucasf/NAS/PRS_GP2/Sumstat/Rizig_et_al_2023_AFR_AAC_metaGWAS_no23andMe_hg38_QCed.txt:AFR,/media/lucasf/NAS/PRS_GP2/Sumstat/GP2_EUR_ONLY_HG38_12162024_rsID_QCed.tsv:EUR
OUT_VCF = /media/lucasf/NAS/PRS_GP2/Results
OUT_SUMSTATS = /media/lucasf/NAS/PRS_GP2/Results
OUTPUT_DIR = /media/lucasf/NAS/PRS_GP2/Results
