[Project]
PROJECT_NAME = Epigen

#coloque @ no numero do cromossomo, ex: Chr@.vcf.gz
[Paths]
VCF_FILE = /home/lucasf/PRS-main/LAI_MSP/Phased_1KGP_Peru_Chr@.vcf.gz
MSP_FILE = /home/lucasf/PRS-main/LAI_MSP/@_query_results.msp

#O nome da Pop tem que estar igual do header LAI do arquivo .msp, ex: EUR, AFR, AMR, EAS, SAS
SUMSTATS_FILE_ANCESTRY = /home/lucasf/PRS-main/Sumstats/Rizig_et_al_2023_AFR_AAC_metaGWAS_no23andMe_hg38_QCed.txt:AFR,/home/lucasf/PRS-main/Sumstats/GP2_EUR_ONLY_HG38_12162024_rsID_QCed.tsv:EUR
OUTPUT_DIR = /home/lucasf/PRS-main/Resultado
